### ISSUE TITLE
Additional Chart adding (Google Sheets Gauge)

### ISSUE THREAD

**Issue by johnnydoboj** [googledatastudio/community-visualizations#23]
Is it possible to add additional Gauge chart to GDS? It is already existing in Google Sheets.

![Screenshot1](https://user-images.githubusercontent.com/4904675/56896995-a1dc1980-6a8d-11e9-89f0-49a52b242712.png)

**Comment by y3l2n** [comment]
Adding a gauge chart to Data Studio is a feature request for the product. Feature requests can be added and upvoted here:
https://support.google.com/datastudio/answer/7340016?hl=en
