### ISSUE TITLE
Source code for standard components

### ISSUE THREAD

**Issue by mdgkyle** [googledatastudio/community-visualizations#24]
I am building a duplicate of the standard table component because I need the columns to be dates and rows to be metrics.

Instead of rewriting the whole component it would be helpful to have the standard components be shared. Allow the community to tweak the components that already exist.

**Comment by mdgkyle** [comment]
I wrote [this component ](https://github.com/mdgkyle/dod-table). It works, but there is a lot to be desired on the styling side. Examples of standard components would help me understand how to make the columns resize and sort by dimensions.

**Comment by y3l2n** [comment]
We don't currently have plans to open-source the standard component source code.

Feel free to add a link to your component to this README:
https://github.com/googledatastudio/experimental-visualizations/tree/master/viz

**Comment by mdgkyle** [comment]
Thanks for your quick response! Any way to request a common style guide for the table structure? I used javascript injection to create a table, but I can't resize columns or add field formatting. Maybe I am missing something in the documentation.

**Comment by y3l2n** [comment]
A couple recommendations:
I might recommend using style elements to take user input for formatting and such: https://developers.google.com/datastudio/visualization/config-reference#styleelement

You could also probably do some resize actions based on user actions like click-and-drag.

In terms of style guide, I'd probably look at table formatting best practices.
