### ISSUE TITLE
Contributing to timeline-v2

### ISSUE THREAD

**Issue by caldav** [googledatastudio/community-visualizations#26]
Hi, I've started using the timeline-v2 viz showcased in [this report](https://datastudio.google.com/u/0/reporting/1A_n0bUPX6wsVcAF2TqwIocBBRA962som/page/cMuf) and I'd like to contribute to it and make it more flexible so it adapts to my use cases, a few examples:
- Dimensions based colors
- Constant margins (I'm using it to display every day as a dot, aligned under a graph using the same date range, but depending on the data (it seems?) the left and right margin of the timeline change, which breaks the alignment) 
- Richer text formatting support in the notes area

Any chance for the source to land in the experimental-visualizations repo?

Thanks

**Comment by y3l2n** [comment]
Hi! For future reference, feel free to open a request like this as an issue in the experimental-visualizations issue.

https://github.com/googledatastudio/experimental-visualizations/pull/28
