### ISSUE TITLE
Codelab Tutorial Issue

### ISSUE THREAD

**Issue by sanyan23** [googledatastudio/community-visualizations#27]
I've worked through the codelab tutorial for creating and implementing a Data Studio community visualisation but am having no success. I've contacted Google and they've confirmed that it is a bug and instructed me to submit a bug.

I'd appreciate is someone can have a look into the following codelab tutorial and let me know of corrective actions.
https://codelabs.developers.google.com/codelabs/community-visualization/#0

Thanks,
Sanyan

**Comment by y3l2n** [comment]
Can you provide a screenshot/description of the errors that you are encountering, and at which step things fail? A component ID that reproduces the issue would help with debugging.

**Comment by jquinter** [comment]
I also have tried the codelab. 

I have setup a gcp project, set the gcs bucket, and modified the manifest.json file accordingly.
![Screenshot 2019-06-11 20 03 21](https://user-images.githubusercontent.com/1566934/59314631-28d30300-8c84-11e9-8269-da91f08c0ccc.png)


When the component id is provided in datastudio, the popup just stayed upon, with the action button stuck in a eternal loop
![Screenshot 2019-06-11 20 03 12](https://user-images.githubusercontent.com/1566934/59314643-31c3d480-8c84-11e9-9071-46b8bed7d9dd.png)

**Comment by jquinter** [comment]
Ooops! in my case this was a relevant hint:
![Screenshot 2019-06-11 20 03 21](https://user-images.githubusercontent.com/1566934/59314822-0f7e8680-8c85-11e9-95ed-b03982621fab.png)

the `manifest.json` file didn't have public access!

Once that was changed, I could add the chart!
![Screenshot 2019-06-11 20 13 14](https://user-images.githubusercontent.com/1566934/59314915-66845b80-8c85-11e9-9929-45caa72f3374.png)

**Comment by jquinter** [comment]
> I've worked through the codelab tutorial for creating and implementing a Data Studio community visualisation but am having no success. I've contacted Google and they've confirmed that it is a bug and instructed me to submit a bug.
> 
> I'd appreciate is someone can have a look into the following codelab tutorial and let me know of corrective actions.
> https://codelabs.developers.google.com/codelabs/community-visualization/#0
> 
> Thanks,
> Sanyan

@sanyan23, did you follow the codelab word by word? notice the manifest template mentions to change the bucket location, but in all the examples a folder is used, so the `component-id` will use this path, and the manifest file should be updated accordingly (unless, of course, you use no folder at all when uploading the relevant files)

**Comment by jquinter** [comment]
After _step 12: Use the color selector style element_, this error triggers in datastudio:

![Screenshot 2019-06-11 20 24 20](https://user-images.githubusercontent.com/1566934/59315242-f1198a80-8c86-11e9-8a30-c74644a367e2.png)

no further details are provided, more than this:

![Screenshot 2019-06-11 20 24 27](https://user-images.githubusercontent.com/1566934/59315261-0098d380-8c87-11e9-9d51-f0c3ca37b1af.png)

This is my final `myViz.js` file:
https://gist.github.com/jquinter/edc26579194e604a2dac8ec21cb66a5f

**Comment by y3l2n** [comment]
@jquinter thank you for the detailed bug report.

It's a bug I didn't quite catch when I updated the codelab recently- the code for step 12 should not have the first line 
```
const dscc = require('@google/dscc1')
```

That's line 2 of your gist. Try again deleting that line of code. I'm updating the codelab now.
