### ISSUE TITLE
The [Showcase] Sankey diagram report has no No Data Set Access

### ISSUE THREAD

**Issue by mhawksey** [googledatastudio/community-visualizations#8]
Trying to load the [[Showcase] Sankey diagram](https://datastudio.google.com/reporting/1hdqhp5dK31BcFInZzmaQOEQdVB54D4gz/page/j9DU) fails  with 
>No Data Set Access
>Insufficient permissions to the underlying data set.

**Comment by y3l2n** [comment]
Replicated and reporting/tracking it internally. Thank you for letting me know. 

Closing the issue because it's being tracked/handled elsewhere.
